//! Versioned, product-scoped enrollment protocol. Wire data is never authority.
#![forbid(unsafe_code)]
use ed25519_dalek::{Signature, Signer, SigningKey, VerifyingKey};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fmt;

pub mod changes;

pub const VERSION: u16 = 1;
pub const CS_MAIL_POLICY: &str = "cs-mail.bank-ownership.v1";
pub const MAX_LIFETIME: i64 = 900;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Error {
    Invalid,
    Signature,
    Context,
    Expired,
    Conflict,
    Unauthorized,
    Unavailable,
}
impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "identity contract: {self:?}")
    }
}
impl std::error::Error for Error {}

pub fn digest<T: Serialize>(label: &str, value: &T) -> Result<[u8; 32], Error> {
    Ok(Sha256::digest(bytes(label, value)?).into())
}
fn bytes<T: Serialize>(label: &str, value: &T) -> Result<Vec<u8>, Error> {
    serde_json::to_vec(&(label, value)).map_err(|_| Error::Invalid)
}
pub fn random_id() -> Result<String, Error> {
    let mut data = [0u8; 32];
    getrandom::fill(&mut data).map_err(|_| Error::Unavailable)?;
    Ok(data.iter().map(|b| format!("{b:02x}")).collect())
}
fn text_valid(s: &str) -> bool {
    !s.is_empty() && s.len() <= 256 && !s.chars().any(char::is_control)
}
fn lifetime(start: i64, end: i64, now: i64) -> Result<(), Error> {
    if start < 0 || end <= start || end - start > MAX_LIFETIME {
        return Err(Error::Invalid);
    }
    if now < start || now >= end {
        return Err(Error::Expired);
    }
    Ok(())
}
fn sign<T: Serialize>(label: &str, value: &T, secret: &[u8; 32]) -> Result<Vec<u8>, Error> {
    Ok(SigningKey::from_bytes(secret)
        .sign(&bytes(label, value)?)
        .to_bytes()
        .to_vec())
}
fn verify<T: Serialize>(
    label: &str,
    value: &T,
    signature: &[u8],
    key: &[u8; 32],
) -> Result<(), Error> {
    VerifyingKey::from_bytes(key)
        .map_err(|_| Error::Signature)?
        .verify_strict(
            &bytes(label, value)?,
            &Signature::from_slice(signature).map_err(|_| Error::Signature)?,
        )
        .map_err(|_| Error::Signature)
}

/// Opaque, product-scoped reference. It is not the service's global SubjectId.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(try_from = "String", into = "String")]
pub struct ProductSubjectRef(String);
impl ProductSubjectRef {
    pub fn as_str(&self) -> &str {
        &self.0
    }
}
impl TryFrom<String> for ProductSubjectRef {
    type Error = Error;
    fn try_from(value: String) -> Result<Self, Error> {
        if !text_valid(&value) {
            return Err(Error::Invalid);
        }
        Ok(Self(value))
    }
}
impl From<ProductSubjectRef> for String {
    fn from(value: ProductSubjectRef) -> Self {
        value.0
    }
}

/// Immutable intent generated by the product backend. Account is an opaque wire ID.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct EnrollmentIntent {
    pub version: u16,
    pub product: String,
    pub operation: String,
    pub account: String,
    pub challenge: String,
    pub initial_key: [u8; 32],
    pub enrollment_digest: [u8; 32],
    pub bank_digest: [u8; 32],
    pub created_at: i64,
    pub expires_at: i64,
}
impl EnrollmentIntent {
    /// Stable enrollment identity survives renewal of short-lived authentication context.
    pub fn same_enrollment(&self, other: &Self) -> bool {
        self.version == other.version
            && self.product == other.product
            && self.operation == other.operation
            && self.account == other.account
            && self.initial_key == other.initial_key
            && self.enrollment_digest == other.enrollment_digest
            && self.bank_digest == other.bank_digest
    }

    pub fn validate(&self, now: i64) -> Result<(), Error> {
        if self.version != VERSION
            || ![
                &self.product,
                &self.operation,
                &self.account,
                &self.challenge,
            ]
            .iter()
            .all(|s| text_valid(s))
            || self.challenge.len() < 32
            || self.enrollment_digest == [0; 32]
            || self.bank_digest == [0; 32]
        {
            return Err(Error::Invalid);
        }
        VerifyingKey::from_bytes(&self.initial_key).map_err(|_| Error::Invalid)?;
        lifetime(self.created_at, self.expires_at, now)
    }
    pub fn prove_possession(&self, secret: &[u8; 32]) -> Result<Vec<u8>, Error> {
        sign("identity/device-enrollment/v1", self, secret)
    }
    pub fn verify_possession(&self, proof: &[u8]) -> Result<(), Error> {
        verify(
            "identity/device-enrollment/v1",
            self,
            proof,
            &self.initial_key,
        )
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Ownership {
    Confirmed,
    ReviewRequired,
    Denied,
}
/// Produced by the bank integration after authenticating provider evidence.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct BankOwnershipClaims {
    pub product: String,
    pub operation: String,
    pub challenge: String,
    pub login_issuer: String,
    pub login_subject: String,
    pub bank_digest: [u8; 32],
    pub evidence_ref: String,
    pub ownership: Ownership,
    pub issued_at: i64,
    pub expires_at: i64,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SignedBankOwnership {
    pub claims: BankOwnershipClaims,
    pub signature: Vec<u8>,
}
impl SignedBankOwnership {
    pub fn sign(claims: BankOwnershipClaims, secret: &[u8; 32]) -> Result<Self, Error> {
        let signature = sign("identity/bank-ownership/v1", &claims, secret)?;
        Ok(Self { claims, signature })
    }
    pub fn verify(
        &self,
        key: &[u8; 32],
        intent: &EnrollmentIntent,
        issuer: &str,
        subject: &str,
        now: i64,
    ) -> Result<Ownership, Error> {
        verify(
            "identity/bank-ownership/v1",
            &self.claims,
            &self.signature,
            key,
        )?;
        let c = &self.claims;
        if c.product != intent.product
            || c.operation != intent.operation
            || c.challenge != intent.challenge
            || c.bank_digest != intent.bank_digest
            || c.login_issuer != issuer
            || c.login_subject != subject
            || !text_valid(&c.evidence_ref)
        {
            return Err(Error::Context);
        }
        lifetime(c.issued_at, c.expires_at, now)?;
        Ok(c.ownership)
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DecisionClaims {
    pub issuer: String,
    pub intent: EnrollmentIntent,
    pub subject_ref: ProductSubjectRef,
    pub binding_version: u64,
    pub security_version: u64,
    pub policy: String,
    pub evidence_ref: String,
    pub issued_at: i64,
    pub expires_at: i64,
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SignedDecision {
    pub signing_key: String,
    pub claims: DecisionClaims,
    pub signature: Vec<u8>,
}
impl SignedDecision {
    pub fn sign(claims: DecisionClaims, secret: &[u8; 32]) -> Result<Self, Error> {
        let signing_key =
            decision_key_id(&SigningKey::from_bytes(secret).verifying_key().to_bytes())?;
        let signature = sign(
            "identity/enrollment-decision/v2",
            &(&signing_key, &claims),
            secret,
        )?;
        Ok(Self {
            signing_key,
            claims,
            signature,
        })
    }
}
/// Immutable trust-ring entry. Revocation removes an entry; overlap is explicit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DecisionKey {
    pub id: String,
    pub key: [u8; 32],
    pub valid_from: i64,
    pub valid_until: Option<i64>,
}
pub fn decision_key_id(key: &[u8; 32]) -> Result<String, Error> {
    Ok(digest("identity/decision-key/v1", key)?
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect())
}
impl DecisionKey {
    pub fn new(key: [u8; 32], valid_from: i64, valid_until: Option<i64>) -> Result<Self, Error> {
        let value = Self {
            id: decision_key_id(&key)?,
            key,
            valid_from,
            valid_until,
        };
        value.validate()?;
        Ok(value)
    }
    fn validate(&self) -> Result<(), Error> {
        VerifyingKey::from_bytes(&self.key).map_err(|_| Error::Invalid)?;
        if self.id != decision_key_id(&self.key)?
            || self.valid_from < 0
            || self.valid_until.is_some_and(|end| end <= self.valid_from)
        {
            return Err(Error::Invalid);
        }
        Ok(())
    }
}
/// Deployment configuration, never selected by the enrolling caller.
#[derive(Debug, Clone)]
pub struct DecisionVerifier {
    issuer: String,
    product: String,
    keys: Vec<DecisionKey>,
}
/// Proof cannot be constructed or deserialized by application callers.
#[derive(Debug, Clone)]
pub struct VerifiedDecision(DecisionClaims);
impl VerifiedDecision {
    pub fn claims(&self) -> &DecisionClaims {
        &self.0
    }
}
impl DecisionVerifier {
    pub fn new(issuer: String, product: String, key: [u8; 32]) -> Result<Self, Error> {
        if !text_valid(&issuer) || !text_valid(&product) {
            return Err(Error::Invalid);
        }
        VerifyingKey::from_bytes(&key).map_err(|_| Error::Invalid)?;
        Ok(Self {
            issuer,
            product,
            keys: vec![DecisionKey::new(key, 0, None)?],
        })
    }
    pub fn with_keys(
        issuer: String,
        product: String,
        keys: Vec<DecisionKey>,
    ) -> Result<Self, Error> {
        if !text_valid(&issuer) || !text_valid(&product) || keys.is_empty() {
            return Err(Error::Invalid);
        }
        for (i, key) in keys.iter().enumerate() {
            key.validate()?;
            if keys[..i].iter().any(|other| other.id == key.id) {
                return Err(Error::Conflict);
            }
        }
        Ok(Self {
            issuer,
            product,
            keys,
        })
    }
    pub fn product(&self) -> &str {
        &self.product
    }
    fn key_at(&self, id: &str, issued: i64, now: i64) -> Result<&[u8; 32], Error> {
        let key = self
            .keys
            .iter()
            .find(|key| key.id == id)
            .ok_or(Error::Signature)?;
        if issued < key.valid_from
            || now < key.valid_from
            || key
                .valid_until
                .is_some_and(|end| now >= end || issued >= end)
        {
            return Err(Error::Expired);
        }
        Ok(&key.key)
    }
    pub fn verify(
        &self,
        decision: &SignedDecision,
        expected: &EnrollmentIntent,
        now: i64,
    ) -> Result<VerifiedDecision, Error> {
        let key = self.key_at(&decision.signing_key, decision.claims.issued_at, now)?;
        verify(
            "identity/enrollment-decision/v2",
            &(&decision.signing_key, &decision.claims),
            &decision.signature,
            key,
        )?;
        let c = &decision.claims;
        expected.validate(now)?;
        if c.issuer != self.issuer
            || c.intent != *expected
            || c.intent.product != self.product
            || c.policy != CS_MAIL_POLICY
            || c.binding_version != 1
            || c.security_version != 1
            || !text_valid(c.subject_ref.as_str())
            || !text_valid(&c.evidence_ref)
            || c.expires_at > expected.expires_at
            || c.issued_at < expected.created_at
        {
            return Err(Error::Context);
        }
        lifetime(c.issued_at, c.expires_at, now)?;
        Ok(VerifiedDecision(c.clone()))
    }
}

#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", content = "data", deny_unknown_fields)]
pub enum Request {
    ChangeIdentity {
        intent: changes::ChangeIntent,
        oidc_token: String,
        bank: SignedBankOwnership,
        device_proof: Vec<u8>,
    },
    SecurityEvents {
        after_version: u64,
        subject_ref: ProductSubjectRef,
    },
    Enroll {
        intent: EnrollmentIntent,
        oidc_token: String,
        bank: SignedBankOwnership,
        device_proof: Vec<u8>,
    },
    Lookup {
        operation: String,
    },
    Confirm {
        decision: SignedDecision,
    },
}
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct SignedRequest {
    pub product: String,
    pub request: Request,
    pub signature: Vec<u8>,
}
impl SignedRequest {
    pub fn sign(product: String, request: Request, secret: &[u8; 32]) -> Result<Self, Error> {
        let signature = sign("identity/product-request/v1", &(&product, &request), secret)?;
        Ok(Self {
            product,
            request,
            signature,
        })
    }
    pub fn verify(&self, product: &str, key: &[u8; 32]) -> Result<(), Error> {
        if self.product != product {
            return Err(Error::Context);
        }
        verify(
            "identity/product-request/v1",
            &(&self.product, &self.request),
            &self.signature,
            key,
        )
    }
}
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", content = "data", deny_unknown_fields)]
pub enum Response {
    IdentityChanged(Box<changes::SignedSecurityEvent>),
    SecurityEvents(Vec<changes::SignedSecurityEvent>),
    Eligible(Box<SignedDecision>),
    ReviewRequired,
    Denied,
    Missing,
    Confirmed,
    Rejected(Error),
}
/// A client failure preserves its underlying transport cause without putting it on the wire.
#[derive(Debug)]
pub struct ClientError {
    code: Error,
    source: Option<Box<dyn std::error::Error + Send + Sync>>,
}
impl ClientError {
    pub fn with_source(
        code: Error,
        source: impl std::error::Error + Send + Sync + 'static,
    ) -> Self {
        Self {
            code,
            source: Some(Box::new(source)),
        }
    }
    pub fn code(&self) -> Error {
        self.code
    }
}
impl From<Error> for ClientError {
    fn from(code: Error) -> Self {
        Self { code, source: None }
    }
}
impl fmt::Display for ClientError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.code.fmt(f)
    }
}
impl std::error::Error for ClientError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        self.source
            .as_ref()
            .map(|source| &**source as &(dyn std::error::Error + 'static))
    }
}
/// Implemented by an authenticated service transport; no shared database is required.
pub trait IdentityClient {
    fn call(&self, request: &SignedRequest) -> Result<Response, ClientError>;
}

/// Verified decisions cannot be manufactured by deserializing caller JSON.
/// ```compile_fail
/// fn accepts_json<T: for<'de> serde::Deserialize<'de>>() {}
/// accepts_json::<identity_contract::VerifiedDecision>();
/// ```
const _: () = ();

#[cfg(test)]
mod tests {
    use super::*;
    fn intent() -> EnrollmentIntent {
        EnrollmentIntent {
            version: VERSION,
            product: "cs-mail/test".into(),
            operation: "op".into(),
            account: "1".into(),
            challenge: "c".repeat(64),
            initial_key: SigningKey::from_bytes(&[1; 32]).verifying_key().to_bytes(),
            enrollment_digest: [2; 32],
            bank_digest: [3; 32],
            created_at: 100,
            expires_at: 200,
        }
    }
    #[test]
    fn decisions_are_bound_to_all_context_and_time() {
        let i = intent();
        let d = SignedDecision::sign(
            DecisionClaims {
                issuer: "identity".into(),
                intent: i.clone(),
                subject_ref: "scoped".to_string().try_into().unwrap(),
                binding_version: 1,
                security_version: 1,
                policy: CS_MAIL_POLICY.into(),
                evidence_ref: "bank".into(),
                issued_at: 100,
                expires_at: 200,
            },
            &[4; 32],
        )
        .unwrap();
        let v = DecisionVerifier::new(
            "identity".into(),
            i.product.clone(),
            SigningKey::from_bytes(&[4; 32]).verifying_key().to_bytes(),
        )
        .unwrap();
        assert!(v.verify(&d, &i, 150).is_ok());
        for now in [99, 200] {
            assert!(v.verify(&d, &i, now).is_err());
        }
        for field in 0..5 {
            let mut other = i.clone();
            match field {
                0 => other.product = "phoros/test".into(),
                1 => other.operation = "other".into(),
                2 => other.initial_key = [7; 32],
                3 => other.bank_digest = [8; 32],
                _ => other.enrollment_digest = [9; 32],
            }
            assert!(v.verify(&d, &other, 150).is_err());
        }
        let mut tampered = d.clone();
        tampered.claims.subject_ref = "attacker".to_string().try_into().unwrap();
        assert!(v.verify(&tampered, &i, 150).is_err());
        assert!(i
            .verify_possession(&i.prove_possession(&[1; 32]).unwrap())
            .is_ok());
        assert!(i
            .verify_possession(&i.prove_possession(&[2; 32]).unwrap())
            .is_err());
    }
}
