[package]
name = "identity-adapters"
version = "0.1.0"
edition = "2021"
[dependencies]
identity-model = { path = "../identity-model" }
jsonwebtoken = "9.3.1"
reqwest = { version = "0.12.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
ed25519-dalek = "2.2.0"
ring = "0.17.14"
serde_json = "1"
fen-store = { path = "../fen-store" }
